# Generated by Django 3.1.7 on 2021-04-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='listing_slug',
        ),
        migrations.AddField(
            model_name='post',
            name='listing_content',
            field=models.TextField(default='***'),
        ),
    ]
