# Generated by Django 3.1.7 on 2021-04-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20210401_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='listing_content',
            field=models.TextField(null=True),
        ),
    ]
