# Generated by Django 3.1.7 on 2021-04-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20210401_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_title', models.CharField(max_length=200, unique=True)),
                ('listing_content', models.TextField(null=True)),
                ('listing_location', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Kisumu', 'Kisumu'), ('Mombasa', 'Mombasa'), ('Thika', 'Thika'), ('Nakuru', 'Nakuru')], default='Nairobi', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
