# Generated by Django 3.1.7 on 2021-04-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20210401_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_status',
            field=models.CharField(choices=[('Rented', 'Rented'), ('Sold', 'Sold'), ('For Rent', 'For Rent'), ('For Sale', 'For Sale'), ('Pending', 'Pending')], default='For Rent', max_length=15),
        ),
    ]
