# Generated by Django 3.1.7 on 2021-04-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_listing_listing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('Apartments', 'Apartments'), ('Commercial', 'Commercial'), ('Hotels & Lodges', 'Hotels & Lodges'), ('Land/Plots', 'Land/Plots'), ('Other', 'Other')], default='Apartments', help_text='Select the correct type that represents this listing.', max_length=15)),
                ('number_of_bedrooms', models.IntegerField(help_text='Enter the total number of Bedrooms in this listing.')),
                ('number_of_bathrooms', models.IntegerField(help_text='Enter the total number of bathrooms in this listing.')),
                ('furniture', models.CharField(choices=[('Yes', 'Furnished'), ('No', 'Unfurnished')], default='Yes', max_length=3)),
            ],
        ),
    ]
