# Generated by Django 3.1.7 on 2021-04-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_listinginformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingInformation',
        ),
        migrations.AddField(
            model_name='listing',
            name='air_conditioning',
            field=models.CharField(blank=True, help_text='Does this listing have an AC unit or similar?', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='balcony_or_terrace',
            field=models.CharField(blank=True, help_text='Does this listing include a balcony or a terrace?', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='dstv_or_cable',
            field=models.CharField(blank=True, help_text='Does this listing come with a DSTV / Cable connection?', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='furniture',
            field=models.CharField(choices=[('Furnished', 'Yes'), ('Unfurnished', 'No')], default='Yes', max_length=15),
        ),
        migrations.AddField(
            model_name='listing',
            name='garden',
            field=models.CharField(blank=True, help_text='Does this listing come with a garden?', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='gym',
            field=models.CharField(blank=True, help_text='Does this listing include a gym?', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='internet',
            field=models.CharField(blank=True, help_text='Is there a pre-existing internet connection in this listing?', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='kitchen_appliances',
            field=models.CharField(blank=True, help_text='Select the appliances that are available in the current listing.', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('Apartments', 'Apartments'), ('Commercial', 'Commercial'), ('Hotels & Lodges', 'Hotels & Lodges'), ('Land/Plots', 'Land/Plots'), ('Other', 'Other')], default='Apartments', help_text='Select the correct type that represents this listing.', max_length=15),
        ),
        migrations.AddField(
            model_name='listing',
            name='number_of_bathrooms',
            field=models.IntegerField(default=0, help_text='Enter the total number of bathrooms in this listing.'),
        ),
        migrations.AddField(
            model_name='listing',
            name='number_of_bedrooms',
            field=models.IntegerField(default=0, help_text='Enter the total number of Bedrooms in this listing.'),
        ),
        migrations.AddField(
            model_name='listing',
            name='parking_information',
            field=models.CharField(default='Ample Parking', help_text='Enter information about the parking situation.', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='power_information',
            field=models.CharField(default='Available', help_text='Enter information about the power/energy supply.', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='security_information',
            field=models.CharField(default='Adequate', help_text='Enter information about the security situation.', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='service_fee',
            field=models.CharField(blank=True, help_text='Does this listing have a service fee?', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='swimming_pool',
            field=models.CharField(blank=True, help_text='Does this listing include a swimming pool?', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='water_information',
            field=models.CharField(default='Available', help_text='Enter information about the water supply.', max_length=100),
        ),
    ]
