# Generated by Django 3.1.7 on 2021-04-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_auto_20210401_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_title',
            field=models.CharField(help_text='Add the title of this listing.', max_length=500, unique=True),
        ),
    ]
