# Generated by Django 3.1.7 on 2021-04-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_auto_20210401_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('Apartments', 'Apartments'), ('Houses', 'Houses'), ('Commercial', 'Commercial'), ('Hotels & Lodges', 'Hotels & Lodges'), ('Land/Plots', 'Land/Plots'), ('Other', 'Other')], default='Apartments', help_text='Select the correct type that represents this listing.', max_length=15),
        ),
    ]
