# Generated by Django 3.1.7 on 2021-04-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_auto_20210402_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='parking_information',
            field=models.CharField(default='', help_text='Enter information about the parking situation.', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='power_information',
            field=models.CharField(default='', help_text='Enter information about the power/energy supply.', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='security_information',
            field=models.CharField(default='', help_text='Enter information about the security situation.', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='water_information',
            field=models.CharField(default='', help_text='Enter information about the water supply.', max_length=100),
        ),
    ]
