# Generated by Django 3.1.7 on 2021-04-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_locations_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='sub_title',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='title',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
