# Generated by Django 3.1.7 on 2021-04-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20210401_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='location',
            name='title',
        ),
        migrations.AddField(
            model_name='location',
            name='header_caption',
            field=models.CharField(help_text='If you wish to display a caption under the title, enter it here.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='header_title',
            field=models.CharField(help_text="If you don't want to use the main title in the page header, enter a new one here.", max_length=50, null=True),
        ),
    ]
